name: Tests

on:
  push:
  pull_request:

jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '7.4'
          - '8.0'

        symfony:
          - '5.0.*'
          - '5.1.*'
          - '5.2.*'
          - '5.3.*'

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Determine composer cache directory
        id: composer-cache
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.directory }}
          key: ${{ matrix.php }}-${{ matrix.symfony }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ matrix.php }}-${{ matrix.symfony }}-composer-

      - name: Install symfony version
        run: composer require --dev --no-update symfony/symfony=${{ matrix.symfony }}

      - name: Install dependencies
        run: composer update --prefer-dist --prefer-stable

      - name: Run tests
        run: |
          mkdir -p build/logs
          ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v
